/**
 * What the server sends back when we ask for matches on a keyword
 */
var testResponse = {
    "results": [{
        "animated": false,
        "author": "BioDigital",
        "cost": 0.0,
        "create_date_time": null,
        "description": "You should see a doctor if you have a lump or swelling in your neck. Doctors use a physical exam, blood tests, imaging tests, and a biopsy to diagnose thyroid cancer. Treatment depends on the type of cancer you have and how far the cancer has spread. Many patients receive a combination of treatments. They may include surgery, radioactive iodine, hormone treatment, radiation therapy, chemotherapy, or targeted therapy. Targeted therapy uses substances that attack cancer cells without harming normal cells. (source: NIH Medline Plus)",
        "embed_url": "/widget/?m=production/maleAdult/thyroid_cancer_demo.json",
        "embed_url_path": "/widget/",
        "featured": true,
        "groups": [],
        "hires_img_url": "",
        "id": "Condition.content.production.maleAdult.thyroid_cancer_demo.json",
        "module_name": "production/maleAdult/thyroid_cancer_demo.json",
        "premium": false,
        "rotatable_url": "",
        "sex": "male",
        "stream_url": "/mstream/modules/production/maleAdult/thyroid_cancer_demo.json",
        "tags": ["ICD-10:C73", "Oncology", "Pharma/Device", "Thyroid", "Diabetes and Endocrinology", "standalone", "Ear, Nose and Throat", "Head and Neck", "male", "condition", "Endocrine System", "featured"],
        "thumbnail_url": "/thumbnails?s=male&dn=thyroid+cancer",
        "title": "Thyroid Cancer",
        "type": "module"
    }, {
        "animated": false,
        "author": "BioDigital",
        "cost": 0.0,
        "create_date_time": null,
        "description": "Thyroid cancer begins when cells in the thyroid gland begin to change and grow uncontrollably, forming a nodule (tumor). Ninety percent of all thyroid nodules are benign (noncancerous), but a few are malignant (cancerous). An estimated 37,200 new cases of thyroid cancer are diagnosed each year in the United States. Women are nearly three times more likely to develop a thyroid tumor than men. The chance of diagnosis has risen considerably in recent years, due in part to improved detection of small tumors with ultrasound, PET, and CT imaging. Unlike many other types of cancer, which are more common in older people, thyroid cancer occurs mainly in adults between the ages 20 and 55. It is also one of the most curable types of cancer â€” approximately 95 percent of people with a thyroid tumor survive at least five years beyond their diagnosis. (Source: Memorial Sloan-Kettering Cancer Center)",
        "embed_url": "/widget/?m=production/maleAdult/thyroid_cancer_t2_cross_section.json",
        "embed_url_path": "/widget/",
        "featured": false,
        "groups": [],
        "hires_img_url": "",
        "id": "Condition.content.production.maleAdult.thyroid_cancer_t2_cross_section.json",
        "module_name": "production/maleAdult/thyroid_cancer_t2_cross_section.json",
        "premium": false,
        "rotatable_url": "",
        "sex": "male",
        "stream_url": "/mstream/modules/production/maleAdult/thyroid_cancer_t2_cross_section.json",
        "tags": ["ICD-10:C73", "Oncology", "Pharma/Device", "Thyroid", "Diabetes and Endocrinology", "standalone", "Ear, Nose and Throat", "Head and Neck", "male", "condition", "Endocrine System"],
        "thumbnail_url": "/thumbnails?s=male&dn=thyroid+cancer+stage+t2",
        "title": "Thyroid Cancer Stage T2",
        "type": "module"
    }, {
        "animated": false,
        "author": "BioDigital",
        "cost": 0.0,
        "create_date_time": null,
        "description": "Thyroid cancer begins when cells in the thyroid gland begin to change and grow uncontrollably, forming a nodule (tumor). Ninety percent of all thyroid nodules are benign (noncancerous), but a few are malignant (cancerous). An estimated 37,200 new cases of thyroid cancer are diagnosed each year in the United States. Women are nearly three times more likely to develop a thyroid tumor than men. The chance of diagnosis has risen considerably in recent years, due in part to improved detection of small tumors with ultrasound, PET, and CT imaging. Unlike many other types of cancer, which are more common in older people, thyroid cancer occurs mainly in adults between the ages 20 and 55. It is also one of the most curable types of cancer â€” approximately 95 percent of people with a thyroid tumor survive at least five years beyond their diagnosis. (Source: Memorial Sloan-Kettering Cancer Center)",
        "embed_url": "/widget/?m=production/maleAdult/thyroid_cancer_m1.json",
        "embed_url_path": "/widget/",
        "featured": false,
        "groups": [],
        "hires_img_url": "",
        "id": "Condition.content.production.maleAdult.thyroid_cancer_m1.json",
        "module_name": "production/maleAdult/thyroid_cancer_m1.json",
        "premium": false,
        "rotatable_url": "",
        "sex": "male",
        "stream_url": "/mstream/modules/production/maleAdult/thyroid_cancer_m1.json",
        "tags": ["ICD-10:C73", "Oncology", "Pharma/Device", "Thyroid", "Diabetes and Endocrinology", "standalone", "Ear, Nose and Throat", "Head and Neck", "male", "condition", "Endocrine System"],
        "thumbnail_url": "/thumbnails?s=male&dn=thyroid+cancer+stage+m1",
        "title": "Thyroid Cancer Stage M1",
        "type": "module"
    }, {
        "animated": false,
        "author": "BioDigital",
        "cost": 0.0,
        "create_date_time": null,
        "description": "Thyroid cancer begins when cells in the thyroid gland begin to change and grow uncontrollably, forming a nodule (tumor). Ninety percent of all thyroid nodules are benign (noncancerous), but a few are malignant (cancerous). An estimated 37,200 new cases of thyroid cancer are diagnosed each year in the United States. Women are nearly three times more likely to develop a thyroid tumor than men. The chance of diagnosis has risen considerably in recent years, due in part to improved detection of small tumors with ultrasound, PET, and CT imaging. Unlike many other types of cancer, which are more common in older people, thyroid cancer occurs mainly in adults between the ages 20 and 55. It is also one of the most curable types of cancer â€” approximately 95 percent of people with a thyroid tumor survive at least five years beyond their diagnosis. (Source: Memorial Sloan-Kettering Cancer Center)",
        "embed_url": "/widget/?m=production/maleAdult/thyroid_cancer_t4a_recurrent_laryngeal.json",
        "embed_url_path": "/widget/",
        "featured": false,
        "groups": [],
        "hires_img_url": "",
        "id": "Condition.content.production.maleAdult.thyroid_cancer_t4a_recurrent_laryngeal.json",
        "module_name": "production/maleAdult/thyroid_cancer_t4a_recurrent_laryngeal.json",
        "premium": false,
        "rotatable_url": "",
        "sex": "male",
        "stream_url": "/mstream/modules/production/maleAdult/thyroid_cancer_t4a_recurrent_laryngeal.json",
        "tags": ["ICD-10:C73", "Oncology", "Pharma/Device", "Thyroid", "Diabetes and Endocrinology", "standalone", "Ear, Nose and Throat", "Head and Neck", "male", "condition", "Endocrine System"],
        "thumbnail_url": "/thumbnails?s=male&dn=thyroid+cancer+stage+t4a+-+recurrent+laryngeal+involvement",
        "title": "Thyroid Cancer Stage T4a - Recurrent Laryngeal Involvement",
        "type": "module"
    }, {
        "animated": false,
        "author": "BioDigital",
        "cost": 0.0,
        "create_date_time": null,
        "description": "Thyroid cancer begins when cells in the thyroid gland begin to change and grow uncontrollably, forming a nodule (tumor). Ninety percent of all thyroid nodules are benign (noncancerous), but a few are malignant (cancerous). An estimated 37,200 new cases of thyroid cancer are diagnosed each year in the United States. Women are nearly three times more likely to develop a thyroid tumor than men. The chance of diagnosis has risen considerably in recent years, due in part to improved detection of small tumors with ultrasound, PET, and CT imaging. Unlike many other types of cancer, which are more common in older people, thyroid cancer occurs mainly in adults between the ages 20 and 55. It is also one of the most curable types of cancer â€” approximately 95 percent of people with a thyroid tumor survive at least five years beyond their diagnosis. (Source: Memorial Sloan-Kettering Cancer Center)",
        "embed_url": "/widget/?m=production/maleAdult/thyroid_cancer_t4a_trachea.json",
        "embed_url_path": "/widget/",
        "featured": false,
        "groups": [],
        "hires_img_url": "",
        "id": "Condition.content.production.maleAdult.thyroid_cancer_t4a_trachea.json",
        "module_name": "production/maleAdult/thyroid_cancer_t4a_trachea.json",
        "premium": false,
        "rotatable_url": "",
        "sex": "male",
        "stream_url": "/mstream/modules/production/maleAdult/thyroid_cancer_t4a_trachea.json",
        "tags": ["ICD-10:C73", "Oncology", "Pharma/Device", "Thyroid", "Diabetes and Endocrinology", "standalone", "Ear, Nose and Throat", "Head and Neck", "male", "condition", "Endocrine System"],
        "thumbnail_url": "/thumbnails?s=male&dn=thyroid+cancer+stage+t4a+-+tracheal+involvement",
        "title": "Thyroid Cancer Stage T4a - Tracheal Involvement",
        "type": "module"
    }, {
        "animated": false,
        "author": "BioDigital",
        "cost": 0.0,
        "create_date_time": null,
        "description": "Thyroid cancer begins when cells in the thyroid gland begin to change and grow uncontrollably, forming a nodule (tumor). Ninety percent of all thyroid nodules are benign (noncancerous), but a few are malignant (cancerous). An estimated 37,200 new cases of thyroid cancer are diagnosed each year in the United States. Women are nearly three times more likely to develop a thyroid tumor than men. The chance of diagnosis has risen considerably in recent years, due in part to improved detection of small tumors with ultrasound, PET, and CT imaging. Unlike many other types of cancer, which are more common in older people, thyroid cancer occurs mainly in adults between the ages 20 and 55. It is also one of the most curable types of cancer â€” approximately 95 percent of people with a thyroid tumor survive at least five years beyond their diagnosis. (Source: Memorial Sloan-Kettering Cancer Center)",
        "embed_url": "/widget/?m=production/maleAdult/thyroid_cancer_n1b.json",
        "embed_url_path": "/widget/",
        "featured": false,
        "groups": [],
        "hires_img_url": "",
        "id": "Condition.content.production.maleAdult.thyroid_cancer_n1b.json",
        "module_name": "production/maleAdult/thyroid_cancer_n1b.json",
        "premium": false,
        "rotatable_url": "",
        "sex": "male",
        "stream_url": "/mstream/modules/production/maleAdult/thyroid_cancer_n1b.json",
        "tags": ["ICD-10:C73", "Oncology", "Pharma/Device", "Thyroid", "Diabetes and Endocrinology", "standalone", "Ear, Nose and Throat", "Head and Neck", "male", "condition", "Endocrine System"],
        "thumbnail_url": "/thumbnails?s=male&dn=thyroid+cancer+stage+n1b",
        "title": "Thyroid Cancer Stage N1b",
        "type": "module"
    }, {
        "animated": false,
        "author": "BioDigital",
        "cost": 0.0,
        "create_date_time": null,
        "description": "Thyroid cancer begins when cells in the thyroid gland begin to change and grow uncontrollably, forming a nodule (tumor). Ninety percent of all thyroid nodules are benign (noncancerous), but a few are malignant (cancerous). An estimated 37,200 new cases of thyroid cancer are diagnosed each year in the United States. Women are nearly three times more likely to develop a thyroid tumor than men. The chance of diagnosis has risen considerably in recent years, due in part to improved detection of small tumors with ultrasound, PET, and CT imaging. Unlike many other types of cancer, which are more common in older people, thyroid cancer occurs mainly in adults between the ages 20 and 55. It is also one of the most curable types of cancer â€” approximately 95 percent of people with a thyroid tumor survive at least five years beyond their diagnosis. (Source: Memorial Sloan-Kettering Cancer Center)",
        "embed_url": "/widget/?m=production/maleAdult/thyroid_cancer_t1a_cross_section.json",
        "embed_url_path": "/widget/",
        "featured": false,
        "groups": [],
        "hires_img_url": "",
        "id": "Condition.content.production.maleAdult.thyroid_cancer_t1a_cross_section.json",
        "module_name": "production/maleAdult/thyroid_cancer_t1a_cross_section.json",
        "premium": false,
        "rotatable_url": "",
        "sex": "male",
        "stream_url": "/mstream/modules/production/maleAdult/thyroid_cancer_t1a_cross_section.json",
        "tags": ["ICD-10:C73", "Oncology", "Pharma/Device", "Thyroid", "scrubber", "Diabetes and Endocrinology", "standalone", "Ear, Nose and Throat", "Head and Neck", "male", "condition", "Endocrine System"],
        "thumbnail_url": "/thumbnails?s=male&dn=thyroid+cancer+stage+t1a",
        "title": "Thyroid Cancer Stage T1a",
        "type": "module"
    }, {
        "animated": false,
        "author": "BioDigital",
        "cost": 0.0,
        "create_date_time": null,
        "description": "Thyroid cancer begins when cells in the thyroid gland begin to change and grow uncontrollably, forming a nodule (tumor). Ninety percent of all thyroid nodules are benign (noncancerous), but a few are malignant (cancerous). An estimated 37,200 new cases of thyroid cancer are diagnosed each year in the United States. Women are nearly three times more likely to develop a thyroid tumor than men. The chance of diagnosis has risen considerably in recent years, due in part to improved detection of small tumors with ultrasound, PET, and CT imaging. Unlike many other types of cancer, which are more common in older people, thyroid cancer occurs mainly in adults between the ages 20 and 55. It is also one of the most curable types of cancer â€” approximately 95 percent of people with a thyroid tumor survive at least five years beyond their diagnosis. (Source: Memorial Sloan-Kettering Cancer Center)",
        "embed_url": "/widget/?m=production/maleAdult/thyroid_cancer_t4a_cricoid.json",
        "embed_url_path": "/widget/",
        "featured": false,
        "groups": [],
        "hires_img_url": "",
        "id": "Condition.content.production.maleAdult.thyroid_cancer_t4a_cricoid.json",
        "module_name": "production/maleAdult/thyroid_cancer_t4a_cricoid.json",
        "premium": false,
        "rotatable_url": "",
        "sex": "male",
        "stream_url": "/mstream/modules/production/maleAdult/thyroid_cancer_t4a_cricoid.json",
        "tags": ["ICD-10:C73", "Oncology", "Pharma/Device", "Thyroid", "Diabetes and Endocrinology", "standalone", "Ear, Nose and Throat", "Head and Neck", "male", "condition", "Endocrine System"],
        "thumbnail_url": "/thumbnails?s=male&dn=thyroid+cancer+stage+t4a+-+cricoid+cartilage+involvement",
        "title": "Thyroid Cancer Stage T4a - Cricoid Cartilage Involvement",
        "type": "module"
    }, {
        "animated": false,
        "author": "BioDigital",
        "cost": 0.0,
        "create_date_time": null,
        "description": "Thyroid cancer begins when cells in the thyroid gland begin to change and grow uncontrollably, forming a nodule (tumor). Ninety percent of all thyroid nodules are benign (noncancerous), but a few are malignant (cancerous). An estimated 37,200 new cases of thyroid cancer are diagnosed each year in the United States. Women are nearly three times more likely to develop a thyroid tumor than men. The chance of diagnosis has risen considerably in recent years, due in part to improved detection of small tumors with ultrasound, PET, and CT imaging. Unlike many other types of cancer, which are more common in older people, thyroid cancer occurs mainly in adults between the ages 20 and 55. It is also one of the most curable types of cancer â€” approximately 95 percent of people with a thyroid tumor survive at least five years beyond their diagnosis. (Source: Memorial Sloan-Kettering Cancer Center)",
        "embed_url": "/widget/?m=production/maleAdult/thyroid_cancer_t4a_esophagus.json",
        "embed_url_path": "/widget/",
        "featured": false,
        "groups": [],
        "hires_img_url": "",
        "id": "Condition.content.production.maleAdult.thyroid_cancer_t4a_esophagus.json",
        "module_name": "production/maleAdult/thyroid_cancer_t4a_esophagus.json",
        "premium": false,
        "rotatable_url": "",
        "sex": "male",
        "stream_url": "/mstream/modules/production/maleAdult/thyroid_cancer_t4a_esophagus.json",
        "tags": ["ICD-10:C73", "Oncology", "Pharma/Device", "Thyroid", "Diabetes and Endocrinology", "standalone", "Ear, Nose and Throat", "Head and Neck", "male", "condition", "Endocrine System"],
        "thumbnail_url": "/thumbnails?s=male&dn=thyroid+cancer+stage+t4a+-+esophageal+involvement",
        "title": "Thyroid Cancer Stage T4a - Esophageal Involvement",
        "type": "module"
    }, {
        "animated": false,
        "author": "BioDigital",
        "cost": 0.0,
        "create_date_time": null,
        "description": "Thyroid cancer begins when cells in the thyroid gland begin to change and grow uncontrollably, forming a nodule (tumor). Ninety percent of all thyroid nodules are benign (noncancerous), but a few are malignant (cancerous). An estimated 37,200 new cases of thyroid cancer are diagnosed each year in the United States. Women are nearly three times more likely to develop a thyroid tumor than men. The chance of diagnosis has risen considerably in recent years, due in part to improved detection of small tumors with ultrasound, PET, and CT imaging. Unlike many other types of cancer, which are more common in older people, thyroid cancer occurs mainly in adults between the ages 20 and 55. It is also one of the most curable types of cancer â€” approximately 95 percent of people with a thyroid tumor survive at least five years beyond their diagnosis. (Source: Memorial Sloan-Kettering Cancer Center)",
        "embed_url": "/widget/?m=production/maleAdult/thyroid_cancer_t3_cross_section.json",
        "embed_url_path": "/widget/",
        "featured": false,
        "groups": [],
        "hires_img_url": "",
        "id": "Condition.content.production.maleAdult.thyroid_cancer_t3_cross_section.json",
        "module_name": "production/maleAdult/thyroid_cancer_t3_cross_section.json",
        "premium": false,
        "rotatable_url": "",
        "sex": "male",
        "stream_url": "/mstream/modules/production/maleAdult/thyroid_cancer_t3_cross_section.json",
        "tags": ["ICD-10:C73", "Oncology", "Pharma/Device", "Thyroid", "Diabetes and Endocrinology", "standalone", "Ear, Nose and Throat", "Head and Neck", "male", "condition", "Endocrine System"],
        "thumbnail_url": "/thumbnails?s=male&dn=thyroid+cancer+stage+t3",
        "title": "Thyroid Cancer Stage T3",
        "type": "module"
    }, {
        "animated": false,
        "author": "BioDigital",
        "cost": 0.0,
        "create_date_time": null,
        "description": "Thyroid cancer begins when cells in the thyroid gland begin to change and grow uncontrollably, forming a nodule (tumor). Ninety percent of all thyroid nodules are benign (noncancerous), but a few are malignant (cancerous). An estimated 37,200 new cases of thyroid cancer are diagnosed each year in the United States. Women are nearly three times more likely to develop a thyroid tumor than men. The chance of diagnosis has risen considerably in recent years, due in part to improved detection of small tumors with ultrasound, PET, and CT imaging. Unlike many other types of cancer, which are more common in older people, thyroid cancer occurs mainly in adults between the ages 20 and 55. It is also one of the most curable types of cancer â€” approximately 95 percent of people with a thyroid tumor survive at least five years beyond their diagnosis. (Source: Memorial Sloan-Kettering Cancer Center)",
        "embed_url": "/widget/?m=production/maleAdult/thyroid_cancer_t4b_prevertebral_mm.json",
        "embed_url_path": "/widget/",
        "featured": false,
        "groups": [],
        "hires_img_url": "",
        "id": "Condition.content.production.maleAdult.thyroid_cancer_t4b_prevertebral_mm.json",
        "module_name": "production/maleAdult/thyroid_cancer_t4b_prevertebral_mm.json",
        "premium": false,
        "rotatable_url": "",
        "sex": "male",
        "stream_url": "/mstream/modules/production/maleAdult/thyroid_cancer_t4b_prevertebral_mm.json",
        "tags": ["ICD-10:C73", "Oncology", "Pharma/Device", "Thyroid", "Diabetes and Endocrinology", "standalone", "Ear, Nose and Throat", "Head and Neck", "male", "condition", "Endocrine System"],
        "thumbnail_url": "/thumbnails?s=male&dn=thyroid+cancer+stage+t4b",
        "title": "Thyroid Cancer Stage T4b",
        "type": "module"
    }, {
        "animated": false,
        "author": "BioDigital",
        "cost": 0.0,
        "create_date_time": null,
        "description": "Thyroid cancer begins when cells in the thyroid gland begin to change and grow uncontrollably, forming a nodule (tumor). Ninety percent of all thyroid nodules are benign (noncancerous), but a few are malignant (cancerous). An estimated 37,200 new cases of thyroid cancer are diagnosed each year in the United States. Women are nearly three times more likely to develop a thyroid tumor than men. The chance of diagnosis has risen considerably in recent years, due in part to improved detection of small tumors with ultrasound, PET, and CT imaging. Unlike many other types of cancer, which are more common in older people, thyroid cancer occurs mainly in adults between the ages 20 and 55. It is also one of the most curable types of cancer â€” approximately 95 percent of people with a thyroid tumor survive at least five years beyond their diagnosis. (Source: Memorial Sloan-Kettering Cancer Center)",
        "embed_url": "/widget/?m=production/maleAdult/thyroid_cancer_n1a.json",
        "embed_url_path": "/widget/",
        "featured": false,
        "groups": [],
        "hires_img_url": "",
        "id": "Condition.content.production.maleAdult.thyroid_cancer_n1a.json",
        "module_name": "production/maleAdult/thyroid_cancer_n1a.json",
        "premium": false,
        "rotatable_url": "",
        "sex": "male",
        "stream_url": "/mstream/modules/production/maleAdult/thyroid_cancer_n1a.json",
        "tags": ["ICD-10:C73", "Oncology", "Pharma/Device", "Thyroid", "Diabetes and Endocrinology", "standalone", "Ear, Nose and Throat", "Head and Neck", "male", "condition", "Endocrine System"],
        "thumbnail_url": "/thumbnails?s=male&dn=thyroid+cancer+stage+n1a",
        "title": "Thyroid Cancer Stage N1a",
        "type": "module"
    }, {
        "animated": false,
        "author": "BioDigital",
        "cost": 0.0,
        "create_date_time": null,
        "description": "Thyroid cancer begins when cells in the thyroid gland begin to change and grow uncontrollably, forming a nodule (tumor). Ninety percent of all thyroid nodules are benign (noncancerous), but a few are malignant (cancerous). An estimated 37,200 new cases of thyroid cancer are diagnosed each year in the United States. Women are nearly three times more likely to develop a thyroid tumor than men. The chance of diagnosis has risen considerably in recent years, due in part to improved detection of small tumors with ultrasound, PET, and CT imaging. Unlike many other types of cancer, which are more common in older people, thyroid cancer occurs mainly in adults between the ages 20 and 55. It is also one of the most curable types of cancer â€” approximately 95 percent of people with a thyroid tumor survive at least five years beyond their diagnosis. (Source: Memorial Sloan-Kettering Cancer Center)",
        "embed_url": "/widget/?m=production/maleAdult/thyroid_cancer_t1b_cross_section.json",
        "embed_url_path": "/widget/",
        "featured": false,
        "groups": [],
        "hires_img_url": "",
        "id": "Condition.content.production.maleAdult.thyroid_cancer_t1b_cross_section.json",
        "module_name": "production/maleAdult/thyroid_cancer_t1b_cross_section.json",
        "premium": false,
        "rotatable_url": "",
        "sex": "male",
        "stream_url": "/mstream/modules/production/maleAdult/thyroid_cancer_t1b_cross_section.json",
        "tags": ["ICD-10:C73", "Oncology", "Pharma/Device", "Thyroid", "Diabetes and Endocrinology", "standalone", "Ear, Nose and Throat", "Head and Neck", "male", "condition", "Endocrine System"],
        "thumbnail_url": "/thumbnails?s=male&dn=thyroid+cancer+stage+t1b",
        "title": "Thyroid Cancer Stage T1b",
        "type": "module"
    }]
};
